name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
on:
  push:
      branches:
        - aliu
        - 0.11.0-aliucord
        - 0.12.0-aliucord

  pull_request:
  workflow_dispatch:

jobs:
  build-linux-compiler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: ccache
        uses: hendrikmuhs/ccache-action@4bcd0c14065d24d92f5e937fae51361c64048b46
        with:
          key: android

      - name: Build compiler
        run: |
          cmake -S . -B build -G Ninja
          cmake --build ./build --config Release --target hermes hermesc hdb hbcdump

      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: | 
            build/bin/hermes 
            build/bin/hermesc 
            build/bin/hdb 
            build/bin/hbcdump
